version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: saas-postgres
    environment:
      POSTGRES_DB: saas_platform
      POSTGRES_USER: saas_user
      POSTGRES_PASSWORD: saas_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - saas-network

  redis:
    image: redis:7-alpine
    container_name: saas-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - saas-network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: saas-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - saas-network

volumes:
  postgres_data:
  redis_data:

networks:
  saas-network:
    driver: bridge 